services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: unless-stopped
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    container_name: "redis-commander"
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    restart: unless-stopped